### ISSUE TITLE
Can't run dotnet Example.DotNetCore.dll

### ISSUE THREAD

**Issue by mackypatt** [david-zoltan/dbdiagramio-mssql#1]
Hi David,

I'm not sure if I'm doing this right - I would love more detail in the steps or to help out with that, could use an ELI5 step-by-step with substeps. Thanks for your time and work on all this, it's great!

**Comment by david-zoltan** [comment]
Hi Makypatt,

Do you see any error message? Or can you tell me where you got stuck?
